# name: Triggered every 1hour
# on:
#   schedule:
#     - cron: "* 1 * * *"

# jobs:
#   setUpAndRun:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       # - uses: actions/checkout@v2
#       #   with:
#       #     fetch-depth: 0
#       # - uses: actions/setup-node@v2
#       #   with:
#       #     node-version: 12
#       # - name: Cache node modules
#       #   uses: actions/cache@v2
#       #   id: npm-cache
#       #   with:
#       #     path: "**/node_modules"
#       #     key: npm-${{ hashFiles('**/package-lock.json') }}
#       #     restore-keys: |
#       #       npm-
#       - name: Install Node.js dependencies
#         run: |-
#           if [[ "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]]; then
#             npm install
#           else
#             echo "Using cache"
#           fi
#         working-directory: ./
#       - name: Run Node.js script
#         run: npm start
#         env:
#           TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
#           TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
#           TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#           TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

name: GitHub Actions Demo
on:
  push:
  pull_request:
  schedule:
    - cron: "* * * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
